checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    nodes:
        analysis:
            environment:
                php: 7.4.12

            dependencies:
                before:
                    - sudo add-apt-repository ppa:ondrej/php
                    - sudo apt update
                    - sudo apt-get install php7.4-gd

            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            environment:
                php: 7.4.12

            dependencies:
                before:
                    - sudo add-apt-repository ppa:ondrej/php
                    - sudo apt update
                    - sudo apt-get install php7.4-gd

                override:
                    - composer self-update
                    - sudo apt-get install -y php-gd
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover
