checks:
    php: true

filter:
    paths:
        - "src/*"

build:
    environment:
        php: 7.4.14

        apt_packages:
            - php-gd

    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

        tests-and-coverage:
            dependencies:
                override:
                    - composer self-update
                    - composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi
            tests:
                override:
                    -
                        command: "./vendor/bin/phpunit --coverage-clover ./coverage.xml"
                        on_node: 1
                        coverage:
                            file: coverage.xml
                            format: php-clover
